name = "supabase-cloudflare-kv"
main = "src/index.js"
compatibility_date = "2022-09-21"
kv_namespaces = [
  { binding = "WEATHER", id = "8226b093883240fa8d6d83fb4e223cde", preview_id = "0c2f6d6f042349f8b39729629d15d3b6" }
]